version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_api_lumi
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: api_lumi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
